name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: '.'

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
    
    - name: 리소스 디렉토리 생성 및 application.yaml 생성
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yaml
      
    - name: 빌드
      run: |
        chmod +x gradlew
        ./gradlew build -x test
      shell: bash
