name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: '.'

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
      
    - name: application.yaml 생성
      run: | 
          echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yml
      working-directory: ${{ env.working-directory }}
      
    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
